import { expect, test } from '@playwright/test';

test('horizontal hand movement reorders cards without submitting a command', async ({ page }) => {
  await page.goto('/');
  await page.locator('#match-seed').fill('1');
  await page.getByRole('button', { name: 'New match' }).click();
  await page.getByRole('button', { name: 'Take first turn' }).click();
  await page.getByRole('button', { name: 'Keep', exact: true }).click();
  await page.getByRole('button', { name: 'Keep', exact: true }).click();
  const cards = page.locator('.hand-fan .card');
  expect(await cards.count()).toBeGreaterThan(1);
  const before = await cards.evaluateAll(nodes => nodes.map(node => (node as HTMLElement).dataset.card));
  const source = await cards.nth(0).boundingBox();
  const target = await cards.nth(2).boundingBox();
  expect(source).not.toBeNull();
  expect(target).not.toBeNull();
  await cards.nth(0).evaluate(card => { (card as HTMLButtonElement).draggable = false; });
  await page.mouse.move(source!.x + source!.width / 2, source!.y + source!.height / 2);
  await page.mouse.down();
  await page.mouse.move(target!.x + target!.width / 2, target!.y + target!.height / 2, { steps: 6 });
  await page.mouse.up();
  const after = await cards.evaluateAll(nodes => nodes.map(node => (node as HTMLElement).dataset.card));
  expect(after).not.toEqual(before);
  await expect(page.getByRole('region', { name: 'Payment draft' })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Pass priority' })).toBeVisible();
});

test('upward hand movement into the battlefield opens a cast draft without casting', async ({ page }) => {
  await page.goto('/');
  await page.locator('#match-seed').fill('1');
  await page.getByRole('button', { name: 'New match' }).click();
  await page.getByRole('button', { name: 'Take first turn' }).click();
  await page.getByRole('button', { name: 'Keep', exact: true }).click();
  await page.getByRole('button', { name: 'Keep', exact: true }).click();
  const card = page.locator('.hand-fan .card.playable').first();
  const cardBounds = await card.boundingBox();
  const fieldBounds = await page.locator('#battlefield-drop').boundingBox();
  expect(cardBounds).not.toBeNull();
  expect(fieldBounds).not.toBeNull();
  await card.evaluate(element => { (element as HTMLButtonElement).draggable = false; });
  await page.mouse.move(cardBounds!.x + cardBounds!.width / 2, cardBounds!.y + cardBounds!.height / 2);
  await page.mouse.down();
  await page.mouse.move(fieldBounds!.x + fieldBounds!.width / 2, fieldBounds!.y + fieldBounds!.height / 2, { steps: 8 });
  await page.mouse.up();
  await expect(page.getByRole('region', { name: 'Payment draft' })).toBeVisible();
  await expect(page.locator('.hand-zone')).toContainText((await card.locator('strong').textContent())!.trim());
  await expect(page.locator('.battlefield')).not.toContainText((await card.locator('strong').textContent())!.trim());
});

test('Escape cancels a hand gesture and an invalid drop does not open a draft', async ({ page }) => {
  await page.goto('/');
  await page.locator('#match-seed').fill('1');
  await page.getByRole('button', { name: 'New match' }).click();
  await page.getByRole('button', { name: 'Take first turn' }).click();
  await page.getByRole('button', { name: 'Keep', exact: true }).click();
  await page.getByRole('button', { name: 'Keep', exact: true }).click();
  const cards = page.locator('.hand-fan .card');
  const before = await cards.evaluateAll(nodes => nodes.map(node => (node as HTMLElement).dataset.card));
  const source = await cards.nth(0).boundingBox();
  const invalidDrop = await page.locator('.top-actions').boundingBox();
  expect(source).not.toBeNull();
  expect(invalidDrop).not.toBeNull();
  await page.mouse.move(source!.x + source!.width / 2, source!.y + source!.height / 2);
  await page.mouse.down();
  await page.mouse.move(source!.x + source!.width / 2 + 70, source!.y + source!.height / 2, { steps: 3 });
  await page.keyboard.press('Escape');
  await page.mouse.up();
  await page.mouse.move(source!.x + source!.width / 2, source!.y + source!.height / 2);
  await page.mouse.down();
  await page.mouse.move(invalidDrop!.x + invalidDrop!.width / 2, invalidDrop!.y + invalidDrop!.height / 2, { steps: 8 });
  await page.mouse.up();
  expect(await cards.evaluateAll(nodes => nodes.map(node => (node as HTMLElement).dataset.card))).toEqual(before);
  await expect(page.getByRole('region', { name: 'Payment draft' })).toHaveCount(0);
  await expect(page.getByRole('button', { name: 'Pass priority' })).toBeVisible();
});

test('lifts the dragged card into a viewport-clamped overlay outside the clipped hand', async ({ page }) => {
  await page.goto('/');
  await page.locator('#match-seed').fill('1');
  await page.getByRole('button', { name: 'New match' }).click();
  await page.getByRole('button', { name: 'Take first turn' }).click();
  await page.getByRole('button', { name: 'Keep', exact: true }).click();
  await page.getByRole('button', { name: 'Keep', exact: true }).click();
  const card = page.locator('.hand-fan .card').first();
  await expect(card).toBeVisible();
  await expect.poll(async () => card.boundingBox()).not.toBeNull();
  const bounds = await card.boundingBox();
  expect(bounds).not.toBeNull();
  await page.mouse.move(bounds!.x + bounds!.width / 2, bounds!.y + bounds!.height / 2);
  await page.mouse.down();
  await page.mouse.move(640, 250, { steps: 3 });
  const preview = page.locator('.gesture-preview');
  await expect(preview).toBeVisible();
  const previewBounds = await preview.boundingBox();
  expect(previewBounds).not.toBeNull();
  expect(previewBounds!.x).toBeGreaterThanOrEqual(0);
  expect(previewBounds!.y).toBeGreaterThanOrEqual(0);
  expect(previewBounds!.x + previewBounds!.width).toBeLessThanOrEqual(1280);
  expect(previewBounds!.y + previewBounds!.height).toBeLessThanOrEqual(720);
  await page.mouse.up();
  await expect(preview).toHaveCount(0);
});

test('clears pointer capture and overlay when the projected match view advances', async ({ page }) => {
  await page.goto('/');
  await page.locator('#match-seed').fill('1');
  await page.getByRole('button', { name: 'New match' }).click();
  await page.getByRole('button', { name: 'Take first turn' }).click();
  await page.getByRole('button', { name: 'Keep', exact: true }).click();
  await page.getByRole('button', { name: 'Keep', exact: true }).click();
  const card = page.locator('.hand-fan .card.playable').first();
  const cardBounds = await card.boundingBox();
  const fieldBounds = await page.locator('#battlefield-drop').boundingBox();
  expect(cardBounds).not.toBeNull();
  expect(fieldBounds).not.toBeNull();
  await page.mouse.move(cardBounds!.x + cardBounds!.width / 2, cardBounds!.y + cardBounds!.height / 2);
  await page.mouse.down();
  await page.mouse.move(fieldBounds!.x + fieldBounds!.width / 2, fieldBounds!.y + fieldBounds!.height / 2, { steps: 8 });
  await expect(page.locator('.gesture-preview')).toBeVisible();
  await page.locator('#pass').evaluate(element => element.dispatchEvent(new MouseEvent('click', { bubbles: true })));
  await expect(page.locator('.gesture-preview')).toHaveCount(0);
  await page.mouse.up();
  await expect(page.getByRole('region', { name: 'Payment draft' })).toHaveCount(0);
});
